amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "scan"

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/sourav/iki_workspace/ros2_ws/src/25ssx2_sh-235839/stage_5/maps/enter_tunnel_real.yaml"

map_saver:
  ros__parameters:
    use_sim_time: true
    save_map_timeout: 5.0
    free_thresh: 0.25
    occupied_thresh: 0.65
    map_subscribe_transient_local: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 2.0
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      min_vel_x: 0.05
      max_vel_x: 0.12
      min_rotational_vel: 0.0
      max_rotational_vel: 0.0
      max_curvature: 0.01

      lookahead_dist: 0.3
      min_lookahead_dist: 0.25
      max_lookahead_dist: 0.4
      use_velocity_scaled_lookahead_dist: false

      use_collision_detection: true
      allow_reversing: false
      use_interpolation: true
      regulate_turning: false

      goal_dist_tol: 0.05
      transform_tolerance: 0.2
      rotate_to_heading_angular_vel: 0.0
      visualize_pursuit_points: true


planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      allow_unknown: true
      use_astar: true
      tolerance: 0.2

local_costmap:
  ros__parameters:
    use_sim_time: true
    update_frequency: 5.0
    publish_frequency: 2.0
    width: 4.0
    height: 4.0
    resolution: 0.05
    rolling_window: true
    robot_radius: 0.10

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: base_scan
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        obstacle_range: 3.0
        raytrace_range: 3.5
        clearing: true
        marking: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.01
      cost_scaling_factor: 3.0


global_costmap:
  ros__parameters:
    use_sim_time: true
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_link
    width: 10.0
    height: 10.0
    resolution: 0.05
    rolling_window: false
    robot_radius: 0.10

    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      enabled: true

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: base_scan
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        obstacle_range: 3.0
        raytrace_range: 3.5
        clearing: true
        marking: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.01
      cost_scaling_factor: 3.0

