version: '3.8'

services:
  ros2-gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=9
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    network_mode: host
    command: >
      bash -c "source /root/ros2_ws/install/setup.bash &&
      ros2 run autorace_real follow_road_real"
