services:
  ros2-gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=5
      - ROS_LOCALHOST_ONLY=0
      - TURTLEBOT3_MODEL=burger
      - USE_SIM_TIME=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    network_mode: host
    command:
    - bash
    - -c
    - |
      source /opt/ros/humble/setup.bash
      source /root/ros2_ws/install/setup.bash
      ros2 run autorace_real autorace_real
      tail -f /dev/null
