services:
  ros2-gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=9
      - ROS_LOCALHOST_ONLY=0
      - TURTLEBOT3_MODEL=burger
      - USE_SIM_TIME=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    network_mode: host
    command:
    - bash
    - -c
    - |
      source /opt/ros/humble/setup.bash
      source /root/ros2_ws/install/setup.bash
      ros2 launch turtlebot3_navigation2 navigation2.launch.py \
        map:=/root/ros2_ws/src/25ssx2_hj-235786/stage_5/maps/entertunnelnew.yaml \
        use_sim_time:=True \
        params_file:=/root/ros2_ws/src/25ssx2_hj-235786/stage_5/maps/nav2_params.yaml &
      sleep 10
      ros2 launch autorace_real enter_tunnel.launch.py
      tail -f /dev/null
